{
 "title": "Monitored.API Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Number of 500 Responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "fields.StatusCode", "id": "2", "settings": { "interval": "1000", "min_doc_count": "0" }, "type": "histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "fields.Application:Monitored.API AND fields.StatusCode:500",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "500 Responses",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "fields.Application:Monitored.API AND fields.StatusCode:500\n",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Number of requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "fields.StatusCode", "id": "2", "settings": { "interval": "1000", "min_doc_count": "0" }, "type": "histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "fields.Application:Monitored.API AND message:\"Request finished*\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Average Backend Processing Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "fields.elapsed", "id": "1", "type": "avg" }
     ],
     "query": "fields.Application:Monitored.API",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Average Request Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "fields.ElapsedMilliseconds", "id": "1", "type": "avg" }
     ],
     "query": "fields.Application:Monitored.API",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Average Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "5m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "fields.ElapsedMilliseconds", "id": "3", "type": "avg" }
     ],
     "query": "fields.Application:Monitored.API",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "75th percentile of latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "fields.ElapsedMilliseconds", "id": "1", "settings": { "percents": [ "75" ] }, "type": "percentiles" }
     ],
     "query": "fields.Application:Monitored.API",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "95th percentile of latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "fields.ElapsedMilliseconds", "id": "1", "settings": { "percents": [ "95" ] }, "type": "percentiles" }
     ],
     "query": "fields.Application:Monitored.API",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "99th percentile of latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "fields.ElapsedMilliseconds", "id": "1", "settings": { "percents": [ "99" ] }, "type": "percentiles" }
     ],
     "query": "fields.Application:Monitored.API",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}