version: '3.4'

services:
  monitored.api:
    container_name: monitoredapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5020:80"
      - "5021:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ~/.vsdbg:/remote_debugger:rw

  sqldata:
    container_name: sqldata
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  seq:
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"
    volumes:
      - /data:/data
    restart: always

  elasticsearch:
    container_name: elasticsearch
    restart: always
    ports:
       - 9200:9200
    environment:
       - discovery.type=single-node
       - network.host=0.0.0.0
       - xpack.security.enabled=false
    volumes:
       - ./deploy/elg/elasticsearch:/usr/share/elasticsearch/data:rw
    ulimits:
      memlock:
        soft: -1
        hard: -1

  grafana:
     container_name: grafana
     ports:
      - "3000:3000"
     volumes:
      - ./deploy/elg/grafana/provisioning:/etc/grafana/provisioning:rw
     restart: always

  opserver:
    container_name: opserver
    ports:
     - "4001:80"
    volumes:
     - ./deploy/opserver/config:/app/Config